name: Experiments in program optimisation
author: Pavel Zemtsov
markdown: redcarpet
pygments: true
timezone: Africa/Johannesburg

collections:
  ququ:
    output: true

TITLE-STORY-CACHE: "How cache affects performance"
TITLE-STORY-BUFFERING: "Effects of stream buffering"

ART-E1:   /2014/04/15/demultiplexing-of-e1.html
ART-E1-C: /2014/05/02/demultiplexing-of-e1-converting-to-C.html
ART-E1-C-SSE: /2014/06/04/fast-e1-de-multiplexing-in-C-using-sse-avx.html
ART-TEMPLATE: /2014/05/07/from-macros-to-templates.html
ART-TRANSPOSING-16X16: /2014/10/01/how-to-transpose-a-16x16-matrix.html
ART-BUG2: /2014/10/21/bug-story-2-unrolling-16x16-transposition.html
ART-JENSEN-DEVICE: /2014/10/28/macro-call-by-name-lambda-jensens-device.html
ART-E1-CACHE: /2014/11/24/how-cache-affects-demultiplexing-of-e1.html 
ART-HASH: /2015/04/24/game-of-life-hash-tables-and-hash-codes.html
ART-MEASURING-HASH: /2015/09/10/hash-functions-disassembling-and-measuring-performance.html
ART-DIVISION-HASH: /2015/09/17/optimising-division-based-hash.html
ART-DIVISION-HASH-MORE: /2015/10/20/more-optimisations-of-division-based-hash-karatsuba-method.html 
ART-MICROBENCHMARK: /2015/10/28/dont-trust-a-micro-benchmark.html
ART-OPTIMISE-LIFE: /2015/12/04/optimising-the-hash-based-life.html 
ART-PEANO: /2015/12/22/implementing-peano-arithmetic.html 

TITLE-E1:   "De-multiplexing of E1 streams in Java"
TITLE-E1-C: "De-multiplexing of E1 stream: converting to C"
TITLE-E1-C-SSE: "Fast E1 de-multiplexing in C using SSE/AVX"
TITLE-TEMPLATE: "From macros to templates"
TITLE-TRANSPOSING-16X16: "How to transpose a 16&times;16 byte matrix using SSE"
TITLE-E1-CACHE: "How cache affects demultiplexing of E1"
TITLE-HASH: "Game of Life, hash tables and hash codes"
TITLE-MEASURING-HASH:  "Hash functions: disassembling and measuring performance"
TITLE-DIVISION-HASH: "Optimising division-based hash functions"
TITLE-DIVISION-HASH-MORE: "More optimisations of division-based hash: Karatsuba's method"
TITLE-MICROBENCHMARK: "Don't trust a micro-benchmark"
TITLE-OPTIMISE-LIFE: "Optimising the hash-based Life" 
TITLE-PEANO: "Implementing Peano arithmetic"

REPO-E1:   https://github.com/pzemtsov/article-E1-demux-Java
REPO-E1-C: https://github.com/pzemtsov/article-E1-demux-C
REPO-ALIASING: https://github.com/pzemtsov/article-GCC-pointer-aliasing
REPO-BUG-TEST: https://github.com/pzemtsov/article-bug-test-code
REPO-JENSEN-DEVICE: https://github.com/pzemtsov/article-jensen-device
REPO-JAVA-CALLBACK: https://github.com/pzemtsov/article-java-callback
REPO-E1-CACHE: https://github.com/pzemtsov/article-e1-cache
REPO-LIFE: https://github.com/pzemtsov/article-life
REPO-PEANO: https://github.com/pzemtsov/article-peano

redcarpet:
 extensions: [smart, tables]
 