name: Notes on program optimisation
markdown: redcarpet
pygments: true
timezone: Africa/Johannesburg

collections:
  ququ:
    output: true

ART-E1:   /2014/04/15/demultiplexing-of-e1.html
ART-E1-C: /2014/05/02/demultiplexing-of-e1-converting-to-C.html
ART-E1-C-SSE: /2014/06/04/fast-e1-de-multiplexing-in-C-using-sse-avx.html
ART-TEMPLATE: /2014/05/07/from-macros-to-templates.html
ART-TRANSPOSING-16X16: /2014/10/01/how-to-transpose-a-16x16-matrix.html
ART-BUG2: /2014/10/21/bug-story-2-unrolling-16x16-transposition.html
ART-JENSEN-DEVICE: /2014/10/28/macro-call-by-name-lambda-jensens-device.html

TITLE-E1:   "De-multiplexing of E1 streams in Java"
TITLE-E1-C: "De-multiplexing of E1 stream: converting to C"
TITLE-E1-C-SSE: "Fast E1 de-multiplexing in C using SSE/AVX"
TITLE-TEMPLATE: "From macros to templates"
TITLE-TRANSPOSING-16X16: "How to transpose a 16&times;16 byte matrix using SSE"

REPO-E1:   https://github.com/pzemtsov/article-E1-demux-Java
REPO-E1-C: https://github.com/pzemtsov/article-E1-demux-C
REPO-ALIASING: https://github.com/pzemtsov/article-GCC-pointer-aliasing
REPO-BUG-TEST: https://github.com/pzemtsov/article-bug-test-code
REPO-JENSEN-DEVICE: https://github.com/pzemtsov/article-jensen-device
REPO-JAVA-CALLBACK: https://github.com/pzemtsov/article-java-callback

redcarpet:
 extensions: [smart, tables]
